### ISSUE TITLE
Clef API dans les commits

### ISSUE THREAD

**Issue by cynddl** [Sakiut/FalltoSkyBot#3]
FYI, il y a quelques fichiers sample avec ```api-key=RGAPI-cf47a674-15d9-404e-aa6e-67ac5282289b``` dans le dépôt. Hors cette clef semble fonctionner sur ```global.api.pvp.net```.

Peut-être utile d'enlever les fichiers (ils resteront dans l'historique par défaut) et de la changer ? :wink:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

**Comment by Sakiut** [comment]
Merci beaucoup pour l'info (JJ a quand même été plus rapide), la modification a été exécutée, et la clé régénérée (j'avais pensé au token mais pas à l'API de Riot ^^')

Merci encore !
