### ISSUE TITLE
Mettre `discordpy` comme dépendance et supprimer le dossier `discord`

### ISSUE THREAD

**Issue by RaitoBezarius** [Sakiut/FalltoSkyBot#4]
Félicitations pour ton projet !

Une petite proposition, il est plutôt fréquent de ne pas mettre sur son repository Git les dépendances utilisés (par Python du moins), en l'occurrence, tu sembles utiliser `discordpy`, il serait plus pratique pour le développement et le déploiement d'ajouter un fichier `requirements.txt` et d'y mettre `discordpy` comme dépendance.

Ainsi, tu pourras supprimer le dossier `discord` et `pip install ./requirements.txt`

**Comment by Sakiut** [comment]
Salut Raito ! Merci pour les félicitations ^^

Pour ce qui est des dépendances `discord.py`, il se trouve que j'ai ajouté quelques fonctionnalités au pack discord classique (les modules `perms.py` et `lol.py`) qui sont essentiels pour faire fonctionner le bot, notamment pour ce qui est des fonctions League of Legends. Je me tâte quant à créer un pack séparé, la question reste donc (de mon côté) en suspens pour le moment... Mais merci encore pour les coms, ça fait plaisir de voir passer l'équipe de Mangaki sur mon projet ;P !

**Comment by Sakiut** [comment]
Ce sera intégré à la prochaine update ;)
